Repository elixirschool/elixirschool, pull requests merged in 2018-08, with the labels that each got.

#1474 [zh-hans] translation for iex-helpers
  zh-hans/lessons/basics/iex-helpers.md
Labels: enhancement

#1477 [zh-hans] error-handling
  zh-hans/lessons/advanced/error-handling.md
Labels: enhancement

#1475 [RU] Interlang
  _data/interlang.yml
Labels: translation

#1486 More transtion updates of Simplified Chinese
  en/index.md
  en/lessons/basics/control-structures.md
  zh-hans/index.md
  zh-hans/lessons/basics/control-structures.md
  zh-hans/lessons/basics/pattern-matching.md
Labels: enhancement

#1487 Update Ecto lesson with cast/3
  en/lessons/specifics/ecto.md
Labels: enhancement

#1484 Update earmark and ex_doc package versions
  en/lessons/basics/documentation.md
Labels: enhancement

#1478 initial attempt on review
  _posts/2018-08-02-functional-web-dev-elixir-otp-phoenix-review.md
Labels: blog

#1488 Merge interlang into locales
  README.md
  _data/contributors.yml
  _data/interlang.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/id.yml
  _data/locales/ja.yml
  _data/locales/ru.yml
  _data/locales/th.yml
  _plugins/elixir_school/generator.rb
  contributors.html
Labels: enhancement
