Repository elixirschool/elixirschool, pull requests merged in 2018-06, with the labels that each got.

#1462 Improve lists appearance
  _assets/stylesheets/components/_list.scss
Labels: fix

#1464 Cleans up the blog title url
  _config.yml
Labels: enhancement

#1460 elixir in action 1st attempt on review
  _posts/2018-05-31-elixir-in-action-review.md
Labels: blog
