Repository elixirschool/elixirschool, pull requests merged in 2018-12, with the labels that each got.

#1635 jwt auth with joken blog post
  _posts/2018-11-29-jwt-auth-with-joken.md
Labels: blog

#1634 Add section on functions and pattern matching.
  en/lessons/basics/functions.md
Labels: enhancement

#1616 [zh-hant] Update basics/collections and strings & Translate libraries/guardian
  zh-hant/lessons/basics/collections.md
  zh-hant/lessons/basics/strings.md
  zh-hant/lessons/libraries/guardian.md
Labels: enhancement, translation

#1592 [ES] Translated basics/date-time chapter
  es/lessons/basics/date-time.md
Labels: translation

#1655 TIL about capturing logs in ExUnit tests
  _data/contributors.yml
  _posts/2018-12-12-til-capture-log-in-exunit-tests.md
Labels: blog

#1614 Ecto Subsection
  _data/contents.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/fr.yml
  _data/locales/gr.yml
  _data/locales/id.yml
  _data/locales/ja.yml
  _data/locales/ko.yml
  _data/locales/pl.yml
  _data/locales/pt.yml
  _data/locales/ru.yml
  _data/locales/vi.yml
  _data/locales/zh-hans.yml
  _data/locales/zh-hant.yml
  en/lessons/ecto/basics.md
  en/lessons/ecto/changesets.md
  en/lessons/specifics/ecto.md
  en/lessons/specifics/ecto_basics.md
  es/lessons/ecto/basics.md
  gr/lessons/ecto/basics.md
  id/lessons/ecto/basics.md
  ja/lessons/ecto/basics.md
  ko/lessons/ecto/basics.md
  pl/lessons/ecto/basics.md
  pt/lessons/ecto/basics.md
  ru/lessons/ecto/basics.md
  vi/lessons/ecto/basics.md
  zh-hans/lessons/ecto/basics.md
  zh-hans/lessons/ecto/changesets.md
  zh-hant/lessons/ecto/basics.md
Labels: enhancement

#1656 TIL: running tests for a child app in an umbrella
  _posts/2018-12-17-til-umbrella-app-child-app-tests.md
Labels: blog

#1653 [PT] update specifics/plug translation
  pt/lessons/specifics/plug.md
Labels: enhancement, translation

#1652 Newline all sentences
  en/lessons/advanced/behaviours.md
  en/lessons/advanced/concurrency.md
  en/lessons/advanced/erlang.md
  en/lessons/advanced/error-handling.md
  en/lessons/advanced/escripts.md
  en/lessons/advanced/gen-stage.md
  en/lessons/advanced/metaprogramming.md
  en/lessons/advanced/otp-concurrency.md
  en/lessons/advanced/otp-distribution.md
  en/lessons/advanced/otp-supervisors.md
  en/lessons/advanced/protocols.md
  en/lessons/advanced/typespec.md
  en/lessons/advanced/umbrella-projects.md
  en/lessons/basics/collections.md
  en/lessons/basics/comprehensions.md
  en/lessons/basics/control-structures.md
  en/lessons/basics/date-time.md
  en/lessons/basics/documentation.md
  en/lessons/basics/enum.md
  en/lessons/basics/functions.md
  en/lessons/basics/iex-helpers.md
  en/lessons/basics/mix-tasks.md
  en/lessons/basics/mix.md
  en/lessons/basics/modules.md
  en/lessons/basics/pattern-matching.md
  en/lessons/basics/pipe-operator.md
  en/lessons/basics/sigils.md
  en/lessons/basics/strings.md
  en/lessons/basics/testing.md
  en/lessons/ecto/changesets.md
  en/lessons/libraries/benchee.md
  en/lessons/libraries/bypass.md
  en/lessons/libraries/guardian.md
  en/lessons/libraries/poolboy.md
  en/lessons/specifics/debugging.md
  en/lessons/specifics/eex.md
  en/lessons/specifics/ets.md
  en/lessons/specifics/mnesia.md
  en/lessons/specifics/plug.md
Labels: discussion, enhancement

#1661 [JA] Bump up basics/pattern-matching to 1.0.2
  ja/lessons/basics/pattern-matching.md
Labels: translation

#1662 [JA] Fix a typo in basic Enum in Japanese
  ja/lessons/basics/enum.md
Labels: enhancement, new lesson

#1663 TIL how to run ecto migrations on production
  _data/contributors.yml
  _posts/2018-12-26-til-how-to-run-ecto-migrations-in-production.md
Labels: blog
