Repository elixirschool/elixirschool, pull requests merged in 2018-02, with the labels that each got.

#1331 Add a section on race conditions with ETS tables
  en/lessons/specifics/ets.md
Labels: enhancement

#1332 Remove redirect from newer lessons
  en/lessons/libraries/bypass.md
  pt/lessons/basics/pattern-matching.md
  pt/lessons/libraries/bypass.md
Labels: fix

#1306 [PT] Updates advanced metaprogramming to latest version
  pt/lessons/advanced/metaprogramming.md
Labels: translation

#1341 [JA] Bump up more articles
  ja/lessons/advanced/concurrency.md
  ja/lessons/advanced/erlang.md
  ja/lessons/advanced/error-handling.md
  ja/lessons/advanced/escripts.md
  ja/lessons/advanced/gen-stage.md
  ja/lessons/advanced/metaprogramming.md
  ja/lessons/advanced/otp-concurrency.md
  ja/lessons/advanced/otp-supervisors.md
  ja/lessons/advanced/protocols.md
  ja/lessons/advanced/umbrella-projects.md
  ja/lessons/basics/comprehensions.md
  ja/lessons/basics/mix-tasks.md
  ja/lessons/basics/strings.md
  ja/lessons/basics/testing.md
  ja/lessons/specifics/ecto.md
  ja/lessons/specifics/eex.md
Labels: enhancement, translation
