Repository elixirschool/elixirschool, pull requests merged in 2018-09, with the labels that each got.

#1500 Fix contributor's alias (@brain-geek)
  _data/contributors.yml
Labels: bug

#1499 the translation of word "string" in zh-hans may be "字符串"
  zh-hans/lessons/basics/sigils.md
Labels: enhancement

#1504 [fr] Update basics.enum lesson to 1.4.0
  fr/lessons/basics/enum.md
Labels: enhancement

#1502 [fr] Update basics.collections lesson to 1.2.3
  fr/lessons/basics/collections.md
Labels: enhancement

#1503 [fr] Update index to 2.0.0
  fr/index.md
Labels: enhancement

#1508 [ru] typo fix
  ru/lessons/advanced/typespec.md
Labels: bug

#1512 [zh-hant] Translate Specifics Section
  zh-hant/lessons/specifics/debugging.md
  zh-hant/lessons/specifics/ecto.md
  zh-hant/lessons/specifics/eex.md
  zh-hant/lessons/specifics/ets.md
  zh-hant/lessons/specifics/mnesia.md
  zh-hant/lessons/specifics/plug.md
Labels: enhancement

#1516 [zh-hans] Translate Advanced - Behaviors to Simplified Chinese
  zh-hans/lessons/advanced/behaviours.md
Labels: translation
