Repository elixirschool/elixirschool, pull requests merged in 2018-04, with the labels that each got.

#1340 [pt] update specifics -> mnesia
  pt/lessons/specifics/mnesia.md
Labels: enhancement, translation

#1407 Reintroduce improvements to the share buttons from #1362
  _includes/share-icons.html
Labels: enhancement

#1406 Update jQuery
  _assets/javascripts/jquery.min.js
Labels: enhancement, website

#1413 Add default `html[lang]` to appendix pages
  _layouts/default.html
Labels: fix

#1418 Improve code block styles
  _assets/stylesheets/main.scss
Labels: enhancement

#1415 Create a page dedicated to contributors
  _config.yml
  _data/contributors.yml
  _data/interlang.yml
  _data/locales/ar.yml
  _data/locales/bg.yml
  _data/locales/bn.yml
  _data/locales/cn.yml
  _data/locales/de.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/fr.yml
  _data/locales/gr.yml
  _data/locales/id.yml
  _data/locales/it.yml
  _data/locales/ja.yml
  _data/locales/ko.yml
  _data/locales/ms.yml
  _data/locales/no.yml
  _data/locales/pl.yml
  _data/locales/pt.yml
  _data/locales/ru.yml
  _data/locales/sk.yml
  _data/locales/ta.yml
  _data/locales/th.yml
  _data/locales/tr.yml
  _data/locales/tw.yml
  _data/locales/uk.yml
  _data/locales/vi.yml
  _includes/section-sidebar-menu.html
  contributors.html
Labels: enhancement

#1417 Remove Contributor.js
  _assets/javascripts/contributors.js
  _assets/javascripts/main.js
  _assets/stylesheets/components/_contributors.scss
  _assets/stylesheets/main.scss
  _includes/section-contributors.html
  _layouts/home.html
  _layouts/page.html
Labels: enhancement

#1425 Improve the README
  README.md
Labels: enhancement
