Repository elixirschool/elixirschool, pull requests merged in 2018-03, with the labels that each got.

#1338 [pt] Update basics -> comprehensions
  pt/lessons/basics/comprehensions.md
Labels: enhancement, translation

#1339 [pt] update advanced -> escripts
  pt/lessons/advanced/escripts.md
Labels: enhancement, translation

#1313 [RU] Improve the section that clarifies the exits trapping
  ru/lessons/advanced/concurrency.md
Labels: translation

#1362 Improve accessibility
  _assets/javascripts/contributors.js
  _includes/head.html
  _includes/social.html
Labels: enhancement

#1360 Update gems
  Gemfile.lock
Labels: enhancement

#1363 Update gems
  Gemfile.lock
Labels: fix

#1370 [RU] Add `Enum.filter/2` section
  ru/lessons/basics/enum.md
Labels: translation
