Repository elixirschool/elixirschool, pull requests merged in 2018-11, with the labels that each got.

#1588 [zh-hans] Keep lesson content up to date
  zh-hans/lessons/basics/collections.md
  zh-hans/lessons/libraries/benchee.md
Labels: Hacktoberfest, enhancement, translation

#1535 Added some docs on the use of ?
  en/lessons/basics/strings.md
Labels: Hacktoberfest, enhancement

#1595 [zh-hans] Update strings lesson about the use of `?`
  zh-hans/lessons/basics/strings.md
Labels: translation

#1596 [PT] add basics/date-time translation
  pt/lessons/basics/date-time.md
Labels: translation

#1541 New post on Ecto.Multi
  _data/contributors.yml
  _posts/2018-10-10-ecto-multi.md
Labels: Hacktoberfest, blog

#1495 update ecto lesson
  en/lessons/specifics/ecto.md
Labels: Hacktoberfest, enhancement

#1573 [UK] Bump pattern matching to 1.0.2
  uk/lessons/basics/pattern-matching.md
Labels: Hacktoberfest, translation

#1598 [zh-hans] update ecto lesson
  en/lessons/specifics/ecto.md
  zh-hans/lessons/specifics/ecto.md
Labels: translation

#1599 Update ecto lesson for Ecto 3
  en/lessons/specifics/ecto.md
Labels: enhancement

#1601 update plug lesson for cowboy2 + plug_cowboy 2
  en/lessons/specifics/plug.md
Labels: enhancement

#1600 Add the reason why first argument of and... cant be any value
  en/lessons/basics/basics.md
Labels: enhancement

#1590 [ES]Writing style and corrections in index for index and basics/basics.md
  es/index.md
  es/lessons/basics/basics.md
Labels: translation

#1528 first iteration of review for elixircards
  _posts/2018-11-14-elixir-cards-review.md
Labels: Hacktoberfest, blog

#1563 Ecto Changesets chapter
  en/lessons/specifics/ecto/changesets.md
Labels: Hacktoberfest, new lesson

#1569 [RU] Bump index to 2.0.0
  ru/index.md
Labels: Hacktoberfest, translation

#1568 [RU] Add Bypass lesson translation
  ru/lessons/libraries/bypass.md
Labels: Hacktoberfest, translation

#1609 [PL] Fixed a typo
  pl/lessons/specifics/ets.md
Labels: enhancement

#1615 [JP] Bump up basics/collections to 1.2.4
  ja/lessons/basics/collections.md
Labels: enhancement, translation

#1623 Update Ruby version and dependecies
  Gemfile
  Gemfile.lock
Labels: bug

#1624 update CONTRIBUTING.md to include version number guide
  CONTRIBUTING.md
Labels: enhancement

#1612 OTP distribution lesson
  _data/contents.yml
  en/lessons/advanced/otp-distribution.md
Labels: new lesson

#1630 a little content fix.
  zh-hans/lessons/basics/comprehensions.md
Labels: enhancement, translation

#1633 [PT] Update control-structures.md
  pt/lessons/basics/control-structures.md
Labels: enhancement, translation

#1632 Create ./fr/lessons/basics/documentation.md
  fr/lessons/basics/documentation.md
Labels: enhancement, translation
