Repository elixirschool/elixirschool, pull requests merged in 2018-10, with the labels that each got.

#1520 [zh-hans] Add Specifics - EEX and Update Specifics - Plug
  zh-hans/lessons/specifics/eex.md
  zh-hans/lessons/specifics/plug.md
Labels: Hacktoberfest, translation

#1530 [PT] Translation: basics/modules
  pt/lessons/basics/modules.md
Labels: Hacktoberfest, translation

#1531 [PT] Translation: basics/sigils
  pt/lessons/basics/sigils.md
Labels: Hacktoberfest, translation

#1532 [PT] Translation: basics/concurrency
  pt/lessons/advanced/concurrency.md
Labels: Hacktoberfest, translation

#1538 [zh-hant] Update all Traditional Chinese Translation to latest Version
  zh-hant/lessons/advanced/otp-concurrency.md
  zh-hant/lessons/advanced/otp-supervisors.md
  zh-hant/lessons/basics/collections.md
  zh-hant/lessons/basics/control-structures.md
  zh-hant/lessons/basics/enum.md
  zh-hant/lessons/basics/functions.md
  zh-hant/lessons/basics/mix-tasks.md
  zh-hant/lessons/basics/modules.md
  zh-hant/lessons/basics/pattern-matching.md
  zh-hant/lessons/basics/pipe-operator.md
  zh-hant/lessons/specifics/ecto.md
  zh-hant/lessons/specifics/plug.md
Labels: Hacktoberfest

#1544 Refactor contributors.yml
  _assets/stylesheets/main.scss
  _data/contributors.yml
  _includes/contributor-profile.html
  _includes/function-getArticle.html
  contributors.html
Labels: Hacktoberfest, enhancement

#1542 [EN] Mo Betta Grammar on Debugging section
  en/lessons/specifics/debugging.md
Labels: Hacktoberfest, enhancement

#1549 [ES] Add spanish transalation of comprehensions lesson
  es/lessons/basics/comprehensions.md
Labels: Hacktoberfest, translation

#1550 [ES] Add spanish translation of Strings lesson
  es/lessons/basics/strings.md
Labels: Hacktoberfest, translation

#1548 [BG] Fixes and updates to basics & collections lessons
  bg/lessons/basics/basics.md
  bg/lessons/basics/collections.md
Labels: Hacktoberfest, translation

#1551 [ES] Add spanish translation of mix tasks lesson
  es/lessons/basics/mix-tasks.md
Labels: Hacktoberfest, translation

#1556 Some additions to the blog
  _assets/stylesheets/main.scss
  _includes/function-getContributor
  _includes/section-author.html
  _includes/section-prevnext.html
  _includes/section-related.html
  _layouts/post.html
Labels: Hacktoberfest, enhancement

#1555 Dark theme
  _assets/javascripts/js.cookie.js
  _assets/javascripts/main.js
  _assets/stylesheets/dark.scss
  _assets/stylesheets/libs/_functions.scss
  _assets/stylesheets/libs/_vars.scss
  _assets/stylesheets/main.scss
  _includes/_head.html
  _includes/_sidebar.html
  _layouts/default.html
Labels: Hacktoberfest, enhancement

#1537 [PT] Translation: specifics/ecto
  pt/lessons/specifics/ecto.md
Labels: Hacktoberfest

#1567 Update index.md
  ar/index.md
Labels: Hacktoberfest, translation

#1559 [RU] Update `basics/modules` to 1.3.0
  ru/lessons/basics/modules.md
Labels: Hacktoberfest, translation

#1560 [RU] Update `basics/collections` to 1.2.3
  ru/lessons/basics/collections.md
Labels: Hacktoberfest, translation

#1562 [RU] Update `advanced/otp-concurrency` to 1.0.3
  ru/lessons/advanced/otp-concurrency.md
Labels: Hacktoberfest, translation

#1561 [RU] Update `basics/pattern-matching` to 1.0.2
  ru/lessons/basics/pattern-matching.md
Labels: Hacktoberfest, translation

#1570 Proofread Benchee lesson
  en/lessons/libraries/benchee.md
Labels: Hacktoberfest

#1572 [UK] Bump collections to 1.2.3 version
  uk/lessons/basics/collections.md
Labels: Hacktoberfest, translation

#1472 New blog post on Umbrella applications
  _posts/2018-10-23-umbrellas-just-when-it-rains.md
Labels: Hacktoberfest, blog, draft

#1576 fix dark mode sidebar border inconsistency
  _assets/stylesheets/dark.scss
Labels: Hacktoberfest, enhancement

#1578 Update contributors.yml
  _data/contributors.yml
  _posts/2018-10-23-umbrellas-just-when-it-rains.md
Labels: enhancement

#1580 Bump elixir / erlang versions to latest stable
  _config.yml
Labels: Hacktoberfest, enhancement

#1581 remove incorrect baseurl
  _config.yml
Labels: Hacktoberfest, enhancement

#1571 Add Date/Time lesson
  _data/contents.yml
  en/lessons/basics/date-time.md
Labels: Hacktoberfest, new lesson

#1566 [ES] Add spanish translation of OTP supervisors lesson
  es/lessons/advanced/otp-supervisors.md
Labels: Hacktoberfest, translation

#1565 [ES] Add spanish translation of OTP concurrency lesson
  es/lessons/advanced/otp-concurrency.md
Labels: Hacktoberfest, translation

#1558 [ES] Updating translation of Mix lesson
  es/lessons/basics/mix.md
Labels: Hacktoberfest

#1583 Fix table headers' text color in dark theme
  _assets/stylesheets/dark.scss
Labels: Hacktoberfest, bug

#1557 [AR] Translate index page and Update basics/basics lesson
  ar/index.md
  ar/lessons/basics/basics.md
Labels: Hacktoberfest, translation

#1543 add localized homepage links
  _includes/section-sidebar-menu.html
  _layouts/default.html
Labels: Hacktoberfest, enhancement

#1585 [zh-hans] Translate basics/date-time lesson
  zh-hans/lessons/basics/date-time.md
Labels: translation

#1586 [style] Make inline code padding smaller
  _assets/stylesheets/base/_typography.scss
Labels: Hacktoberfest, enhancement

#1575 [SK] Basic lessons bump
  sk/lessons/basics/collections.md
  sk/lessons/basics/enum.md
  sk/lessons/basics/functions.md
  sk/lessons/basics/mix-tasks.md
  sk/lessons/basics/modules.md
  sk/lessons/basics/pattern-matching.md
  sk/lessons/basics/testing.md
Labels: Hacktoberfest, translation
