Repository elixirschool/elixirschool, pull requests merged in 2018-05, with the labels that each got.

#1428 Translation Report
  _assets/stylesheets/main.scss
  _data/locales/ar.yml
  _data/locales/bg.yml
  _data/locales/bn.yml
  _data/locales/cn.yml
  _data/locales/de.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/fr.yml
  _data/locales/gr.yml
  _data/locales/id.yml
  _data/locales/it.yml
  _data/locales/ja.yml
  _data/locales/ko.yml
  _data/locales/ms.yml
  _data/locales/no.yml
  _data/locales/pl.yml
  _data/locales/pt.yml
  _data/locales/ru.yml
  _data/locales/sk.yml
  _data/locales/ta.yml
  _data/locales/th.yml
  _data/locales/tr.yml
  _data/locales/tw.yml
  _data/locales/uk.yml
  _data/locales/vi.yml
  _includes/report.html
  _includes/section-sidebar-menu.html
  _plugins/elixir_school/generator.rb
  _plugins/elixir_school/translation_report.rb
  en/index.md
  no/index.md
  tr/index.md
Labels: enhancement

#1431 Rename Appendix to Blog to clear up confusion
  _config.yml
  _data/locales/ar.yml
  _data/locales/bg.yml
  _data/locales/bn.yml
  _data/locales/cn.yml
  _data/locales/de.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/fr.yml
  _data/locales/gr.yml
  _data/locales/id.yml
  _data/locales/it.yml
  _data/locales/ja.yml
  _data/locales/ko.yml
  _data/locales/ms.yml
  _data/locales/no.yml
  _data/locales/pl.yml
  _data/locales/pt.yml
  _data/locales/ru.yml
  _data/locales/sk.yml
  _data/locales/ta.yml
  _data/locales/th.yml
  _data/locales/tr.yml
  _data/locales/tw.yml
  _data/locales/uk.yml
  _data/locales/vi.yml
  _includes/section-home-appendix-posts.html
  _includes/section-sidebar-menu.html
  _layouts/default.html
  _layouts/home.html
  appendix.html
Labels: enhancement

#1434 percentage shown in translation report heading
  _includes/report.html
  _plugins/elixir_school/translation_report.rb
Labels: enhancement

#1437 Slightly improve versioning style of the translation report
  _assets/stylesheets/main.scss
  _includes/report.html
Labels: enhancement

#1436 fix acronym
  en/lessons/specifics/debugging.md
  ko/lessons/specifics/debugging.md
  pt/lessons/specifics/debugging.md
  ru/lessons/specifics/debugging.md
Labels: fix

#1444 Fix empty language name on contributors page
  _data/contributors.yml
Labels: fix

#1443 [RU] Translation report
  _data/locales/ru.yml
Labels: translation

#1445 [UK] Translate global definitions
  _data/locales/uk.yml
Labels: translation

#1453 Translate version severity captions in translation report
  _includes/report.html
  _plugins/elixir_school/translation_report.rb
Labels: enhancement

#1458 Improve GenServer definition to state that it's single process
  en/lessons/advanced/otp-concurrency.md
Labels: enhancement, question
