Repository elixirschool/elixirschool, pull requests merged in 2019-12, with the labels that each got.

#2140 [zh-hans] Update ecto/basics to 2.4.0 to reflect the ecto 3 changes
  zh-hans/lessons/ecto/basics.md
Labels: translation

#2020 [VI] Update `advanced/typespec` to 1.0.3
  vi/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2154 [PT] Fix duplicated word
  pt/lessons/advanced/gen-stage.md
Labels: translation

#2145 [Blog Draft] LiveView Design Patterns: LiveComponent and the Single Responsibility Principle
  _assets/images/live-component-search-form-query-params.png
  _assets/images/live-view-messages-index.png
  _posts/2019-12-29-live-view-live-component.md
Labels: blog
