Repository elixirschool/elixirschool, pull requests merged in 2019-03, with the labels that each got.

#1734 Whitespace/tiny fixes
  en/lessons/basics/date-time.md
  en/lessons/basics/mix-tasks.md
  en/lessons/basics/sigils.md
  en/lessons/ecto/basics.md
  en/lessons/ecto/changesets.md
  en/lessons/ecto/querying.md
  en/lessons/libraries/guardian.md
  en/lessons/libraries/poolboy.md
Labels: enhancement

#1725 update sidebar
  _assets/stylesheets/layout/_sidebar.scss
  _includes/_sidebar.html
  _includes/section-sidebar-menu.html
Labels: enhancement

#1714 [zh-hant] Update multiple lessons to latest Version
  zh-hant/index.md
  zh-hant/lessons/advanced/typespec.md
  zh-hant/lessons/basics/basics.md
  zh-hant/lessons/basics/collections.md
  zh-hant/lessons/basics/documentation.md
  zh-hant/lessons/basics/modules.md
  zh-hant/lessons/ecto/basics.md
  zh-hant/lessons/specifics/mnesia.md
  zh-hant/lessons/specifics/plug.md
Labels: enhancement, translation

#1732 Reword confusing part in Associations lesson
  en/lessons/ecto/associations.md
Labels: enhancement

#1739 Update theme toggler
  _includes/_sidebar.html
Labels: enhancement

#1738 Add 404 error page
  404.html
  _assets/stylesheets/components/_errors.scss
  _assets/stylesheets/main.scss
  _plugins/elixir_school/generator.rb
Labels: enhancement

#1737 [JA] Translate Ecto/Querying
  ja/lessons/ecto/querying.md
Labels: translation

#1741 [ES] Update pattern matching to v1.0.2
  es/lessons/basics/pattern-matching.md
Labels: translation

#1743 Fix Distillery
  en/lessons/libraries/distillery.md
Labels: bug

#1671 Add StreamData lesson
  en/lessons/libraries/stream-data.md
Labels: new lesson

#1749 Change spelling of LiveView
  _posts/2018-03-18-phoenix-live-view.md
Labels: enhancement

#1731 [PT] Translation of Ecto/Changesets
  pt/lessons/ecto/changesets.md
Labels: translation

#1750 Fix path and module name in LiveView post
  _posts/2018-03-18-phoenix-live-view.md
Labels: enhancement

#1752 fix html snippet formatting
  _posts/2018-03-18-phoenix-live-view.md
Labels: enhancement

#1746 [JA] Translate Libraries/Distillery
  ja/lessons/libraries/distillery.md
Labels: translation

#1753 fix: #main div stretching too much
  _assets/stylesheets/layout/_main.scss
Labels: enhancement

#1759 fix unresponsive embeds
  _assets/stylesheets/main.scss
  _posts/2018-03-18-phoenix-live-view.md
Labels: enhancement

#1745 Adds TIL Validations and Constraints Blog Post
  _data/contributors.yml
  _posts/2019-03-25-til-ecto-validations-and-constraints.md
Labels: blog

#1761 [es] update pipe lesson to v1.0.1
  es/lessons/basics/pipe-operator.md
Labels: enhancement, translation

#1763 Fix counters in README
  README.md
Labels: bug

#1764 [ES] Update the basic/functions.md document to v1.2.0
  es/lessons/basics/functions.md
Labels: enhancement, translation

#1769 [ES] Update the basic/documentation.md document to v1.0.3
  es/lessons/basics/documentation.md
Labels: enhancement, translation

#1770 [ES] Update the basic/testing.md document to v1.1.1
  es/lessons/basics/testing.md
Labels: enhancement, translation

#1767 [ES] Update the basic/modules.md document to v1.4.0
  es/lessons/basics/modules.md
Labels: enhancement, translation
