Repository elixirschool/elixirschool, pull requests merged in 2019-11, with the labels that each got.

#2094 Add a small reference to the pipe operator
  en/lessons/basics/basics.md
Labels: Hacktoberfest, enhancement

#2114 [ES] Add Spanish translation of Ecto changesets lesson
  es/lessons/ecto/changesets.md
Labels: Hacktoberfest, translation

#2116 [ES] Add Spanish translation of Mnesia lesson
  es/lessons/specifics/mnesia.md
Labels: Hacktoberfest, translation

#2018 [PL] Update `advanced/typespec` to 1.0.3
  pl/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2023 [UK] Update basics/collections (to 1.3.0)
  uk/lessons/basics/collections.md
Labels: Hacktoberfest, enhancement, translation

#2024 [SK] Add Ecto section and translate ecto/basics.md
  _data/contributors.yml
  _data/locales/sk.yml
  sk/lessons/ecto/basics.md
Labels: Hacktoberfest, translation

#2079 [es] Add spanish translation of behaviours lesson
  es/lessons/advanced/behaviours.md
Labels: Hacktoberfest, translation

#2080 [es] Add spanish translation of typespec lesson
  es/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2081 [es] Add spanish translation of gen_stage lesson
  es/lessons/advanced/gen-stage.md
Labels: Hacktoberfest, translation

#2082 [ES] Add spanish translation of otp-distribution lesson
  es/lessons/advanced/otp-distribution.md
Labels: Hacktoberfest, translation

#2102 [ES] Add spanish translation of nerves lesson
  es/lessons/advanced/nerves.md
Labels: Hacktoberfest, translation

#2074 [PT] Update pt/lessons/basics/functions.md to 1.2.0
  pt/lessons/basics/functions.md
Labels: Hacktoberfest, translation

#1847 [ES] Update basics.md
  es/lessons/basics/basics.md
Labels: Hacktoberfest, translation

#2060 [KO] Update index to 2.0
  ko/index.md
Labels: Hacktoberfest, translation

#2078 [PT] Ecto basics update
  pt/lessons/ecto/basics.md
Labels: Hacktoberfest, translation

#2056 RU translation of lessons/ecto/querying
  ru/lessons/ecto/querying.md
Labels: Hacktoberfest, translation

#2077 [UK] Create uk translation of en/lessons/basics/mix-tasks.md
  uk/lessons/basics/mix-tasks.md
Labels: Hacktoberfest, translation
