Repository elixirschool/elixirschool, pull requests merged in 2019-01, with the labels that each got.

#1553 Ecto: Associations lesson
  _data/contents.yml
  en/lessons/specifics/ecto/associations.md
Labels: Hacktoberfest, draft, new lesson

#1610 Ecto: querying basics
  _data/contents.yml
  en/lessons/ecto/querying.md
Labels: discussion, new lesson

#1644 add distillery to lessons
  _data/contents.yml
  en/lessons/libraries/distillery.md
Labels: new lesson

#1690 fix spelling errors on distillery lesson
  en/lessons/libraries/distillery.md
Labels: enhancement

#1685 [JA] Bump up basics/ modules to 1.3.0
  ja/lessons/basics/modules.md
Labels: translation

#1675 Add elixir kaffe codealong
  _assets/images/kafka-flow-example.png
  _posts/2019-01-03-elixir-kaffe-codealong.md
Labels: blog

#1691 Recursion blog post
  _posts/2019-01-15-recursion.md
Labels: blog

#1670 [zh-hant] update basics/functions (#1669)
  zh-hant/lessons/basics/functions.md
Labels: enhancement, translation

#1699 Bump for Elixir 1.8 release
  _config.yml
Labels: enhancement

#1701 Update collections.md
  en/lessons/basics/collections.md
Labels: enhancement

#1700 Update lesson to mention the new @derive functionality
  bn/lessons/basics/modules.md
  de/lessons/basics/modules.md
  en/lessons/basics/modules.md
  es/lessons/basics/modules.md
  fr/lessons/basics/modules.md
  gr/lessons/basics/modules.md
  id/lessons/basics/modules.md
  it/lessons/basics/modules.md
  ja/lessons/basics/modules.md
  ko/lessons/basics/modules.md
  ms/lessons/basics/modules.md
  no/lessons/basics/modules.md
  pl/lessons/basics/modules.md
  pt/lessons/basics/modules.md
  ru/lessons/basics/modules.md
  sk/lessons/basics/modules.md
  tr/lessons/basics/modules.md
  uk/lessons/basics/modules.md
  vi/lessons/basics/modules.md
  zh-hans/lessons/basics/modules.md
  zh-hant/lessons/basics/modules.md
Labels: enhancement

#1702 miss comma
  zh-hans/lessons/advanced/otp-supervisors.md
Labels: bug

#1703 A tutorial for building web apps with Plug.Router
  _posts/2019-01-25-building-apps-with-plug-router.md
Labels: blog

#1704 [JA] Translate ecto/changesets
  ja/lessons/ecto/changesets.md
Labels: enhancement, translation

#1706 Don't suggest that the concept of an interface will be familiar to Ruby developers
  en/lessons/advanced/typespec.md
Labels: enhancement
