Repository elixirschool/elixirschool, pull requests merged in 2019-02, with the labels that each got.

#1552 [ES] Add spanish translation of iex helpers lesson
  es/lessons/basics/iex-helpers.md
Labels: Hacktoberfest, translation

#1710 TIL about `Process.send_after/4`
  _posts/2019-02-06-til-send-after.md
Labels: blog

#1708 Italian translations for lessons in the basics section
  it/index.md
  it/lessons/basics/basics.md
  it/lessons/basics/collections.md
  it/lessons/basics/control-structures.md
  it/lessons/basics/enum.md
  it/lessons/basics/pattern-matching.md
Labels: WIP, translation

#1711 [zh-hans] Align version for typespec, collections, documentation, mod…
  en/lessons/libraries/distillery.md
  zh-hans/lessons/advanced/typespec.md
  zh-hans/lessons/basics/collections.md
  zh-hans/lessons/basics/documentation.md
  zh-hans/lessons/basics/modules.md
  zh-hans/lessons/libraries/distillery.md
  zh-hans/lessons/specifics/mnesia.md
  zh-hans/lessons/specifics/plug.md
Labels: translation

#1709 Plug & Heroku Deployment Post
  _posts/2019-02-12-putting-a-plug-app-on-heroku.md
Labels: blog

#1722 [zh-hans] Align ecto/changeset and add zh-hans contributors
  _data/contributors.yml
  zh-hans/lessons/ecto/changesets.md
Labels: enhancement

#1716 [JA] Translate Ecto/Associations
  ja/lessons/ecto/associations.md
Labels: translation

#1720 Retrieve all author's metadata from contributors.yml
  _layouts/post.html
Labels: enhancement

#1719 New Blog Post: Supervisory Strategies
  _posts/2019-02-21-supervisor-strategies.md
Labels: blog

#1727 [es] Update basic lesson to v1.2.1
  es/lessons/basics/basics.md
Labels: translation

#1728 [es] update collections to v1.2.5
  es/lessons/basics/collections.md
Labels: translation

#1689 [PT] Translation of Ecto associations lesson for Portuguese
  pt/lessons/ecto/associations.md
Labels: WIP, translation
