Repository elixirschool/elixirschool, pull requests merged in 2019-04, with the labels that each got.

#1775 [RU] Update `basics/basics` to 1.2.1
  ru/lessons/basics/basics.md
Labels: translation

#1780 [RU] basics/pipe-operator: improvements
  ru/lessons/basics/pipe-operator.md
Labels: translation

#1782 [RU] basics/pattern-matching: improvements
  ru/lessons/basics/pattern-matching.md
Labels: translation

#1783 [RU] basics/control-structures: improvements
  ru/lessons/basics/control-structures.md
Labels: translation

#1789 Update dependencies
  Gemfile.lock
Labels: enhancement

#1776 Corrected the functionality of Counter.One and Counter.Three
  _posts/2019-02-21-supervisor-strategies.md
Labels: bug

#1787 Fix unscrollable sidebar
  _assets/javascripts/main.js
  _assets/javascripts/stickyfill.min.js
  _assets/stylesheets/layout/_sidebar.scss
Labels: enhancement

#1788 Localize `Menu` heading
  _data/locales/ar.yml
  _data/locales/bg.yml
  _data/locales/bn.yml
  _data/locales/de.yml
  _data/locales/en.yml
  _data/locales/es.yml
  _data/locales/fr.yml
  _data/locales/gr.yml
  _data/locales/id.yml
  _data/locales/it.yml
  _data/locales/ja.yml
  _data/locales/ko.yml
  _data/locales/ms.yml
  _data/locales/no.yml
  _data/locales/pl.yml
  _data/locales/pt.yml
  _data/locales/ru.yml
  _data/locales/sk.yml
  _data/locales/ta.yml
  _data/locales/th.yml
  _data/locales/tr.yml
  _data/locales/uk.yml
  _data/locales/vi.yml
  _data/locales/zh-hans.yml
  _data/locales/zh-hant.yml
  _includes/section-sidebar-menu.html
Labels: enhancement

#1793 Fix icon class for last commit on Report page
  _includes/report.html
Labels: bug

#1799 Add rel-alternate links
  _includes/_head.html
Labels: enhancement

#1772 LiveView w PubSub blog post
  _assets/images/live_view_pub_sub.png
  _posts/2019-04-11-live-view-with-pub-sub.md
Labels: blog

#1792 Upgrade benchee lessons for 1.0 + some additional content
  _assets/images/benchee_html_graph_sample.png
  en/lessons/libraries/benchee.md
Labels: enhancement

#1784 [RU] basics/functions: update to 1.2.0
  ru/lessons/basics/functions.md
Labels: translation

#1790 [RU] basics/modules: update to 1.4.0
  ru/lessons/basics/modules.md
Labels: translation

#1791 [RU] basics/mix: improvements
  ru/lessons/basics/mix.md
Labels: translation

#1794 [RU] index: improvements
  ru/index.md
Labels: translation

#1779 [zh-hant] Update lessons && Translate basics/date-time
  zh-hant/lessons/basics/date-time.md
  zh-hant/lessons/basics/mix-tasks.md
  zh-hant/lessons/basics/sigils.md
  zh-hant/lessons/ecto/basics.md
  zh-hant/lessons/libraries/guardian.md
Labels: translation

#1795 [RU] basics/testing: improvements
  ru/lessons/basics/testing.md
Labels: translation

#1804 [zh-hans] Add stream-data and align other minor versions
  zh-hans/lessons/basics/date-time.md
  zh-hans/lessons/basics/mix-tasks.md
  zh-hans/lessons/basics/sigils.md
  zh-hans/lessons/ecto/associations.md
  zh-hans/lessons/ecto/basics.md
  zh-hans/lessons/ecto/changesets.md
  zh-hans/lessons/ecto/querying.md
  zh-hans/lessons/libraries/distillery.md
  zh-hans/lessons/libraries/guardian.md
  zh-hans/lessons/libraries/poolboy.md
  zh-hans/lessons/libraries/stream-data.md
Labels: translation

#1807 [JA] Translate Libraries/StreamData
  ja/lessons/libraries/stream-data.md
Labels: translation

#1812 Rephrase Mix lesson details, bump to 1.1.0
  en/lessons/basics/mix.md
Labels: enhancement
