Repository elixirschool/elixirschool, pull requests merged in 2019-05, with the labels that each got.

#1827 Refactor code snippets for readability
  en/lessons/specifics/plug.md
  zh-hans/lessons/specifics/plug.md
  zh-hant/lessons/specifics/plug.md
Labels: enhancement

#1829 Add the workshop announcement for ElixirConf 2019
  _posts/2019-05-01-elixirconf-announcement.md
Labels: blog

#1823 [JA] Translate OTP Distribution into Japanese
  ja/lessons/advanced/otp-distribution.md
Labels: translation

#1837 Adding category and tag support for blog.
  Gemfile
  Gemfile.lock
  _assets/stylesheets/components/_list.scss
  _assets/stylesheets/dark.scss
  _assets/stylesheets/main.scss
  _config.yml
  _data/blog-meta.yml
  _includes/article-preview.html
  _includes/function-getCategoryMeta
  _includes/function-getTagMeta
  _includes/section-home-blog-posts.html
  _includes/section-sidebar-menu.html
  _layouts/archive.html
  _layouts/blog.html
  _layouts/default.html
  _layouts/post.html
  _plugins/elixir_school/generator.rb
  _posts/2018-07-25-ecto-query-composition.md
  _posts/2018-08-02-functional-web-dev-elixir-otp-phoenix-review.md
  _posts/2018-10-10-ecto-multi.md
  _posts/2018-11-29-jwt-auth-with-joken.md
  _posts/2018-12-26-til-how-to-run-ecto-migrations-in-production.md
  _posts/2019-01-03-elixir-kaffe-codealong.md
  _posts/2019-01-15-recursion.md
  _posts/2019-01-25-building-apps-with-plug-router.md
  _posts/2019-02-12-putting-a-plug-app-on-heroku.md
  _posts/2019-03-18-phoenix-live-view.md
  _posts/2019-03-25-til-ecto-validations-and-constraints.md
  _posts/2019-04-11-live-view-with-pub-sub.md
  _posts/2019-05-01-elixirconf-announcement.md
  blog-archive-categories.html
  blog-archive-tags.html
  blog-archive-years.html
  blog.html
  contributors.html
Labels: enhancement

#1836 live view with presence post draft
  _assets/images/live-view-1.png
  _assets/images/live-view-presence-1.png
  _assets/images/live-view-presence-2.png
  _posts/2019-05-06-live-view-with-presence.md
Labels: blog

#1869 [pt] Fix a Portuguese typo in the `basic/control-structures.md`
  pt/lessons/basics/control-structures.md
Labels: translation

#1876 [JA] Translate lessons/ecto/associations
  ja/lessons/ecto/associations.md
Labels: translation

#1786 [PT] Translation of Ecto/Querying
  pt/lessons/ecto/querying.md
Labels: translation

#1800 [RU] basics/mix: improvements
  ru/lessons/basics/mix.md
Labels: translation
