Repository elixirschool/elixirschool, pull requests merged in 2019-10, with the labels that each got.

#2016 [RU] Update `basics/collections` to 1.3.0
  ru/lessons/basics/collections.md
Labels: Hacktoberfest, translation

#2017 [RU] Update `advanced/typespec` to 1.0.3
  ru/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2021 [DE] Update `advanced/typespec` to 1.0.3
  de/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2014 Update `basics/documentation` from 1.0.2 to 1.0.3
  ko/lessons/basics/documentation.md
  pt/lessons/basics/documentation.md
  ru/lessons/basics/documentation.md
  sk/lessons/basics/documentation.md
  tr/lessons/basics/documentation.md
Labels: Hacktoberfest, translation

#2009 Add RSS feed
  feed.xml
Labels: Hacktoberfest

#2019 [PT] Update `advanced/typespec` to 1.0.3
  pt/lessons/advanced/typespec.md
Labels: Hacktoberfest, translation

#2030 [PT] Update Poolboy 1.1.2
  pt/lessons/libraries/poolboy.md
Labels: translation

#2032 [PT] Update Date and Time to 1.0.2
  pt/lessons/basics/date-time.md
Labels: translation

#2029 [PT] Update Guardian 1.0.3
  pt/lessons/libraries/guardian.md
Labels: translation

#2039 [PT] Update Ecto/Querying to 1.0.1
  pt/lessons/ecto/querying.md
Labels: Hacktoberfest

#2006 [ru] Update libraries/benchee.md to 2.0.0
  en/lessons/libraries/benchee.md
  ru/lessons/libraries/benchee.md
Labels: Hacktoberfest

#2041 Update jQuery to 3.4.1
  _assets/javascripts/jquery.min.js
Labels: Hacktoberfest, enhancement

#2043 [JA] Translate enum 1.5.0
  ja/lessons/basics/enum.md
Labels: Hacktoberfest

#2042 [JA] Translate collection 1.3.0
  ja/lessons/basics/collections.md
Labels: Hacktoberfest

#2040 [JA] Translate date-time 1.0.2
  ja/lessons/basics/date-time.md
Labels: Hacktoberfest

#2038 [PT] Update Basics to 1.2.1
  pt/lessons/basics/basics.md
Labels: Hacktoberfest

#1898 [JA] translation otp-supervisors.md v1.0.1 -> 1.1.1
  ja/lessons/advanced/otp-supervisors.md
Labels: Hacktoberfest

#2034 [PT] Update Custom Mix Task to 1.0.3
  pt/lessons/basics/mix-tasks.md
Labels: Hacktoberfest, translation

#2033 [PT] Update Sigils to 1.0.2
  pt/lessons/basics/sigils.md
Labels: Hacktoberfest, translation

#2054 Corrected example for change/2
  en/lessons/ecto/changesets.md
Labels: Hacktoberfest

#2057 [pt] Updates the module lesson, with instropection for structs
  pt/lessons/basics/modules.md
Labels: Hacktoberfest

#2022 [ru] Translate libraries/stream-data.md
  ru/lessons/libraries/stream-data.md
Labels: Hacktoberfest

#2059 [pt] Translate distillery lesson
  pt/lessons/libraries/distillery.md
Labels: Hacktoberfest, translation

#2065 [PT] Update basics/collections (to 1.3.0)
  pt/lessons/basics/collections.md
Labels: Hacktoberfest

#2055 en/lessons/ecto/querying.md > fix few minor issues with code listings
  en/lessons/ecto/querying.md
Labels: Hacktoberfest

#2069 [PT] Update pt/lessons/basics/mix.md to 1.1.0
  pt/lessons/basics/mix.md
Labels: Hacktoberfest

#2070 [PT] Update pt/lessons/basics/testing.md to 1.2.0
  pt/lessons/basics/testing.md
Labels: Hacktoberfest

#2068 [PT] Update pt/lessons/basics/enum.md to 1.5.0
  pt/lessons/basics/enum.md
Labels: Hacktoberfest

#2037 [en] Update libraries/stream-data.md to 1.1.0
  en/lessons/libraries/stream-data.md
Labels: Hacktoberfest

#1995 blog post: Sortable UI with LiveView live links
  _assets/images/live-view-table.png
  _posts/2019-10-20-sorting-a-table-with-live-view-live-links.md
Labels: Hacktoberfest, blog

#2075 Resolves the GitHub security warning
  Gemfile
  Gemfile.lock
Labels: enhancement

#2005 Blog post: How and why we built Admissions
  _posts/2019-10-23-building-admissions.md
Labels: Hacktoberfest, blog

#2089 use the correct categories for posts
  _posts/2019-05-06-live-view-with-presence.md
  _posts/2019-06-04-live-view-with-channels.md
  _posts/2019-08-23-til-ecto-select-merge.md
  _posts/2019-09-12-elixirconf-2019-review.md
  _posts/2019-09-15-releasing-an-umbrella-app-with-docker-and-mix-release.md
  _posts/2019-10-20-sorting-a-table-with-live-view-live-links.md
Labels: Hacktoberfest, enhancement

#2091 [ES] Update Ecto/basics
  en/lessons/ecto/basics.md
  es/lessons/ecto/basics.md
Labels: Hacktoberfest

#2106 [ES] Add spanish translation of Guardian lesson
  es/lessons/libraries/guardian.md
Labels: Hacktoberfest, translation

#2064 [UK] Update uk/lessons/index.md to 2.0.0
  uk/index.md
Labels: Hacktoberfest, translation

#2066 [UK] Update uk/lessons/basics/mix.md to 1.1.0
  uk/lessons/basics/mix.md
Labels: Hacktoberfest, translation

#2067 [PT] Update pt/lessons/ecto/changesets.md to 1.2.0
  pt/lessons/ecto/changesets.md
Labels: Hacktoberfest, translation

#2076 [UK] Create uk translation of en/lessons/basics/comprehensions.md
  uk/lessons/basics/comprehensions.md
Labels: Hacktoberfest, translation
