Repository elixirschool/elixirschool, pull requests merged in 2020-10, with the labels that each got.

#2417 [ES] Adds table of contents for Nerves
  es/lessons/specifics/nerves.md
Labels: hacktoberfest-approved

#2425 Update jQuery to 3.5.1
  _assets/javascripts/jquery.min.js
Labels: enhancement

#2424 Add [rel="noopener"] to GitHub links
  _layouts/page.html
  _layouts/post.html
Labels: enhancement

#2423 Improve time to interactive
  _assets/javascripts/js.cookie.js
  _assets/javascripts/main.js
  _assets/stylesheets/libs/font-awesome/_path.scss
  _includes/_head.html
  _layouts/default.html
Labels: enhancement

#2435 Update collections.md
  gr/lessons/basics/collections.md
Labels: hacktoberfest-approved, translation

#2436 Update enum.md
  gr/lessons/basics/enum.md
Labels: hacktoberfest-approved, translation

#2429 [es] Update collections.md
  es/lessons/basics/collections.md
Labels: translation

#2438 Turn ElixirSchool into a PWA
  _assets/images/favicons/manifest.json
  _assets/images/favicons/splash-512x512.png
  _config.yml
  _includes/_head.html
  manifest.json
  serviceworker.js
Labels: enhancement

#2410 [pt] update Benchee lesson
  pt/lessons/libraries/benchee.md
Labels: hacktoberfest-approved, translation

#2430 [JA] Translate mix 1.1.1
  ja/lessons/basics/mix.md
Labels: translation

#2434 [JA] Translate gen-stage 1.1.1
  ja/lessons/advanced/gen-stage.md
Labels: translation

#2431 [JA] Translate querying 1.2.0
  ja/lessons/ecto/querying.md
Labels: translation

#2432 [JA] Translate enum 1.6.1
  ja/lessons/basics/enum.md
Labels: translation

#2433 [JA] Translate error-handling 1.1.0
  ja/lessons/advanced/error-handling.md
Labels: translation

#2418 [PT] Update lesson: Ecto Associations
  pt/lessons/ecto/associations.md
Labels: translation

#2437 [gr] Update iex-helpers.md
  gr/lessons/basics/iex-helpers.md
Labels: hacktoberfest-approved, translation

#2443 Update umbrella-projects.md
  gr/lessons/advanced/umbrella-projects.md
Labels: hacktoberfest-approved, translation

#2451 [GR] Update gr/lessons/advanced/erlang.md to 1.0.2
  gr/lessons/advanced/erlang.md
Labels: hacktoberfest-approved, translation

#2454 [GR] Update gr/lessons/basics/date-time.md to 1.1.0
  gr/lessons/basics/date-time.md
Labels: hacktoberfest-approved, translation

#2450 creates the full ecto changesets lesson in greek
  gr/lessons/ecto/changesets.md
Labels: hacktoberfest-approved, translation

#2448 bumps ecto/basics to current version
  gr/lessons/ecto/basics.md
Labels: hacktoberfest-approved, translation

#2458 [GR] Bump Concurency to latest version
  gr/lessons/advanced/concurrency.md
Labels: translation

#2466 [GR] Bump functions to latest version
  gr/lessons/basics/functions.md
Labels: translation

#2457 [GR] fully translates ecto/associations
  gr/lessons/ecto/associations.md
Labels: translation

#2472 Greek ecto querying
  gr/lessons/ecto/querying.md
Labels: translation
