Repository elixirschool/elixirschool, pull requests merged in 2021-11, with the labels that each got.

#2715 Add Title Back to Umbrella Apps Blog Post
  posts/2018-10-23-umbrellas-just-when-it-rains.md
Labels: bug, rocketvalidator

#2706 [BN] added translation for intermediate/escripts.md
  lessons/bn/intermediate/escripts.md
Labels: hacktoberfest-approved

#2670 [PL] Update translation: "Comprehensions"
  lessons/pl/basics/comprehensions.md
Labels: hacktoberfest-approved

#2667 [ES] Miscellaneous Benchee
  lessons/es/misc/benchee.md
Labels: hacktoberfest-approved

#2684 [PL] Updated Basic > Basic lesson to 1.3.0
  lessons/pl/basics/basics.md
Labels: hacktoberfest-approved

#2685 [PL] Updated Enum lesson to 1.8.0
  lessons/pl/basics/enum.md
Labels: hacktoberfest-approved

#2686 [PL] Updated Modules lesson to 1.4.1
  lessons/pl/basics/modules.md
Labels: hacktoberfest-approved

#2688 [PL] Updated Strings lesson to 1.2.0
  lessons/pl/basics/strings.md
Labels: hacktoberfest-approved

#2709 [PL] Update translation: "Umbrella Projects"
  lessons/pl/advanced/umbrella_projects.md
Labels: hacktoberfest-approved

#2702 [RU] lessons.intermediate.erlang up to 1.0.3
  lessons/ru/intermediate/erlang.md
Labels: hacktoberfest-approved

#2718 Update CI to build School House
  .github/workflows/ci.yml
Labels: enhancement

#2704 Update functions.md
  lessons/en/basics/functions.md
Labels: hacktoberfest-approved
